<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DefaultTripSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('trips')->insert([
            [
                'destination' => 'Cairo, Egypt',
                'classes' => 'Economy',
                'number_of_travels' => 2,
                'estimated_expenses' => 800.00,
                'budget' => 1000.00,
                'number_of_days' => 5,
                'start_date' => '2026-10-01',
                'end_date' => '2026-10-05',
                'is_fav' => false,
                'style' => 'Cultural & Historical',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'destination' => 'Tokyo, Japan',
                'classes' => 'Economy',
                'number_of_travels' => 2,
                'estimated_expenses' => 1800.00,
                'budget' => 2200.00,
                'number_of_days' => 7,
                'start_date' => '2026-10-15',
                'end_date' => '2026-10-21',
                'is_fav' => false,
                'style' => 'Modern & Cultural',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'destination' => 'Paris, France',
                'classes' => 'Economy',
                'number_of_travels' => 2,
                'estimated_expenses' => 1400.00,
                'budget' => 1800.00,
                'number_of_days' => 5,
                'start_date' => '2026-09-15',
                'end_date' => '2026-09-19',
                'is_fav' => false,
                'style' => 'Cultural & Romantic',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'destination' => 'Rome, Italy',
                'classes' => 'Economy',
                'number_of_travels' => 2,
                'estimated_expenses' => 1200.00,
                'budget' => 1600.00,
                'number_of_days' => 5,
                'start_date' => '2026-10-10',
                'end_date' => '2026-10-14',
                'is_fav' => false,
                'style' => 'Historical',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'destination' => 'Istanbul, Turkey',
                'classes' => 'Economy',
                'number_of_travels' => 2,
                'estimated_expenses' => 700.00,
                'budget' => 1000.00,
                'number_of_days' => 5,
                'start_date' => '2026-09-20',
                'end_date' => '2026-09-24',
                'is_fav' => false,
                'style' => 'Cultural & Historical',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'destination' => 'Dubai, UAE',
                'classes' => 'Business',
                'number_of_travels' => 2,
                'estimated_expenses' => 1800.00,
                'budget' => 2500.00,
                'number_of_days' => 5,
                'start_date' => '2026-11-01',
                'end_date' => '2026-11-05',
                'is_fav' => false,
                'style' => 'Luxury & Shopping',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'destination' => 'Barcelona, Spain',
                'classes' => 'Economy',
                'number_of_travels' => 2,
                'estimated_expenses' => 1100.00,
                'budget' => 1500.00,
                'number_of_days' => 6,
                'start_date' => '2026-09-25',
                'end_date' => '2026-09-30',
                'is_fav' => false,
                'style' => 'Beach & Culture',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'destination' => 'Athens, Greece',
                'classes' => 'Economy',
                'number_of_travels' => 2,
                'estimated_expenses' => 900.00,
                'budget' => 1300.00,
                'number_of_days' => 5,
                'start_date' => '2026-10-20',
                'end_date' => '2026-10-24',
                'is_fav' => false,
                'style' => 'Historical & Leisure',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}